### ISSUE TITLE
Kill Jobs & Timeouts

### ISSUE THREAD

**Issue by jonpwilson** [bbc/hive-runner#113]
Currently, if a job hangs when running (i.e. SVN checkout hangs) the job stays in a running state until killed. We need to add a timeout to automatically kill the job.

**Comment by davidbuckhurst** [comment]
Capability to: 

- set a time in the scheduler after which a job should be killed
- kill a job from the scheduler interface

The runners already have a monitoring process that can kill a running job at the appropriate time

**Comment by Asimk21** [comment]
Done in #181 #184
