### ISSUE TITLE
Cannot set up daemons for 'Mac' in runner

### ISSUE THREAD

**Issue by ambirag** [bbc/hive-runner#167]
When trying to setup runner on Mac OS X(Sierra)
when running "hive_setup my_hive" and choose ios and X , i get the error "Cannot set up daemons for 'Mac'". When i look at the script hive_setup, i see only Linux is handled (if os == 'Linux')
is daemon not necessary for runner?

`LONC02RM2BNG8WL:hive-runner rambighananthan$ hive_setup my_hive
/Users/rambighananthan/.rvm/bin/rvm: line 66: shell_session_update: command not found

+--------+--------+--------+
| Device | Module | Source |
+--------+--------+--------+
+--------+--------+--------+
Operating System: Mac
Set up daemon script: Yes (requires admin access)
Ruby version: ruby-1.9.3-p194 (2 versions available)

1) Add module
2) Change ruby version
3) Do not set up daemon script
X) Continue

> 2
/Users/rambighananthan/.rvm/bin/rvm: line 66: shell_session_update: command not found

Multiple ruby versions available:
+---+-----------------+---------+
| # | Version         |         |
+---+-----------------+---------+
| 1 | ruby-1.9.3-p194 | Default |
| 2 | ruby-2.0.0-p648 |         |
+---+-----------------+---------+

[1 - 2] > 2

+--------+--------+--------+
| Device | Module | Source |
+--------+--------+--------+
+--------+--------+--------+
Operating System: Mac
Set up daemon script: Yes (requires admin access)
Ruby version: ruby-2.0.0-p648 (2 versions available)

1) Add module
2) Change ruby version
3) Do not set up daemon script
X) Continue

> 1

Module name: ios

Module 'hive-runner-ios' from https://rubygems.org/gems/hive-runner-ios
Correct? (y/n) y

+--------+-----------------+-------------------------------------------+
| Device | Module          | Source                                    |
+--------+-----------------+-------------------------------------------+
| ios    | hive-runner-ios | https://rubygems.org/gems/hive-runner-ios |
+--------+-----------------+-------------------------------------------+
Operating System: Mac
Set up daemon script: Yes (requires admin access)
Ruby version: ruby-2.0.0-p648 (2 versions available)

1) Add module
2) Change ruby version
3) Do not set up daemon script
X) Continue

> X
==========================
Setting ruby ... SUCCESS
Creating daemon startup script...FAILED
  Cannot set up daemons for 'Mac'
Executing 'bundle install' ... SUCCESS

Configuration required:

  * Add to config/settings.yml
      - scheduler
      - hive_mind
      - cert
      - cafile
  * Configure these modules in config/settings.yml
      - ios
  * Add to ~/.bashrc
      - export HIVE_CONFIG=/Users/rambighananthan/tools/hive-runner/my_hive/config
  * Move daemons startup script to correct location
      - File currently at '??'
`

**Comment by jrmhaig** [comment]
Hi @ambirag. We are only part way through creating the daemon scripts and currently they only exist for Linux. Your setup should work OK if you start the hive with:

```
hived start
```

while in the directory `/Users/rambighananthan/tools/hive-runner/my_hive` after you have modified `config/settings.yml` as appropriate.

Yes, the setup script shouldn't indicated that it is 'failed' when it hasn't and I'll have a look at fixing that.

**Comment by ambirag** [comment]
@jrmhaig thanks
