### ISSUE TITLE
Warnings raised when running with hashie 3.5.4

### ISSUE THREAD

**Issue by Asimk21** [bbc/hive-runner#183]
Following warning is raised when running hived start 

hashie -v 3.5.4

`W, [2017-02-23T10:29:39.308306 #31956]  WARN -- : You are setting a key that conflicts with a built-in method Hashie::Mash#homes_to_keep defined in Hashie::Mash. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.`

It needs investigation.

**Comment by jrmhaig** [comment]
I am marking this as a bug but it is possibly a bug in https://github.com/intridea/hashie/releases/tag/v3.5.4

**Comment by Asimk21** [comment]
Fixed in hashie v3.5.5.
