### ISSUE TITLE
Hive runner doesn't start with ruby 2.2

### ISSUE THREAD

**Issue by Shashikant86** [bbc/hive-runner#88]
Hive Runner doesn't start with latest ruby Or default config 

Just giving it a try from my own MacBook [Non-BBC]. I got ruby 2.2.1 and installed Hive Runner Gem 

                                 $ hive_setup my -hive

Used X to continue and exported HIVE_CONFIG to .zshrc 

When I ran 

                              $ hived start 

I got following 

                          shashi [workspace/bbc-hive-ci/shashi-hive] → hived start
                                /Users/shashi/.rvm/gems/ruby-2.2.1/gems/chamber-         2.8.0/lib/chamber/settings.rb:276:in `method_missing': undefined method `network' for #<Chamber::Settings:0x007f9af2159b38> (NoMethodError)
	from /Users/shashi/.rvm/gems/ruby-2.2.1/gems/hive-runner-2.0.1/lib/hive.rb:34:in `block in <module:Hive>'
	from /Users/shashi/.rvm/gems/ruby-2.2.1/gems/devicedb_comms-0.1.1/lib/devicedb_comms.rb:17:in `configure'
	from /Users/shashi/.rvm/gems/ruby-2.2.1/gems/hive-runner-2.0.1/lib/hive.rb:33:in `<module:Hive>'
	from /Users/shashi/.rvm/gems/ruby-2.2.1/gems/hive-runner-2.0.1/lib/hive.rb:9:in `<top (required)>'
	from /Users/shashi/.rvm/gems/ruby-2.2.1/gems/hive-runner-2.0.1/bin/hived:16:in `require'
	from /Users/shashi/.rvm/gems/ruby-2.2.1/gems/hive-runner-2.0.1/bin/hived:16:in `<top (required)>'
	from /Users/shashi/.rvm/gems/ruby-2.2.1/bin/hived:23:in `load'
	from /Users/shashi/.rvm/gems/ruby-2.2.1/bin/hived:23:in `<main>'
	from /Users/shashi/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/shashi/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'

My Config looks like this : I got rid of network level config 

                        test:
                       daemon_name: HIVE

                  controllers:
                     shell:
                      # Number of shell workers to allocate
                     workers: 5
                     # Queue for each shell worker
                     queues:
                     - bash
                  # Number of ports to allocate to each shell worker
                    port_range_size: 50
                  name_stub: SHELL_WORKER

                     # Range of ports to be made available to workers
                     ports:
                     minimum: 4000
                       maximum: 5000

                     # Logging configuration
                   logging:
                        directory: /Users/shashi/workspace/bbc-hive-ci/shashi-hive/log
                         pids: /Users/shashi/workspace/bbc-hive-ci/shashi-hive/pids
                        main_filename: hive.log
                       main_level: INFO
                        worker_level: INFO
                       home: /Users/shashi/workspace/bbc-hive-ci/shashi-hive/workspaces
                       homes_to_keep: 5

                         # Timing configuration
                          timings:
                         worker_loop_interval: 5
                          controller_loop_interval: 5

**Comment by Shashikant86** [comment]
@jonpwilson Not sure if need network config like certs required when someone tries to install hive locally

**Comment by davidbuckhurst** [comment]
Yeah -- you will need the network config or the runner will blow up. Add the following:
    network:
      scheduler: http://localhost:3000
